version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-lint:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build

workflows:
  main:
    jobs:
      - build-and-lint
